#!/bin/bash
#SBATCH --mem-per-cpu=4gb
#SBATCH --time=2:00:00
#SBATCH --job-name=LDe
#SBATCH --error=LDe
#SBATCH --output=LDe
#SBATCH --partition=mpi
#SBATCH --ntasks=1

module load python2
module load gcc/4.9.3
module load ldhelmet/1.7
module load egglib
export PYTHONPATH=$PYTHONPATH:~/work/Programs/Biopython/lib/python2.7/site-packages/

indID=$((SLURM_ARRAY_TASK_ID -1))
inName=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16)

scaf="Herato13"
#add theta and mut matrix

#if [ "$(echo "${inName[indID]}")" == 1 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample BC_0411,lativitta_01,lativitta_02,lativitta_03,lativitta_04 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_lat -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample BC_3223,BC_3224,BC_3225,BC_3227,BC_3228,BC_0410,notabilis_01,notabilis_02,notabilis_03,notabilis_04 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_not -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample BC2115,BC2124,STRI_WOM_5779,STRI_WOM_5780,STRI_WOM_5781 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_ama -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample 3661,3662,3663,3664,STRI_WOM_0057,STRI_WOM_0058,STRI_WOM_0059 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_che -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample cyrbia_004,cyrbia_005,cyrbia_023,cyrbia_024 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_cyr -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample STRIWOM1284,STRIWOM5353,STRIWOM5362,STRI_WOM_0033,STRI_WOM_0082,STRI_WOM_0087,Pet_ED3,Pet_ED4,Pet_ED5,Pet_ED6 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_dem -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample GS020redo,GS021redo,NCS_1671,NCS_1672,NCS_1673,NCS_1674,NCS_1675,BC2563,BC2577,BC2578,BC2579, -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_emm -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample NCS_2005,NCS_2012,NCS_2020,NCS_2023,NCS_2025,NCS_2556 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_era -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample BC_3277,BC_3278,BC_3280,BC_3281,BC_3282 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_ety -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample GS012redo,NCS_0471,NCS_0473,NCS_0476,NCS_0478,NCS_0479,NCS_2554,NCS_2555,BC2635,BC2637,BC2638,BC2639 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_fav -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample himera_001,himera_002,himera_003,himera_006,himera_030,BC2565,BC2566,BC2567,BC2570 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_him -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample NCS_1179,NCS_1979,NCS_2080,NCS_2211,NCS_2217,NCS_2574,NCS_2581,NCS_2609 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_hydFG -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample STRI_WOM_0039,STRI_WOM_0040,STRI_WOM_0042,STRI_WOM_0088,STRI_WOM_5193,STRI_WOM_5351 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_hydP -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample CA51,CA53,CA54,CA55,CA56 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_pet -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample STRI_WOM_5732,STRI_WOM_5742,STRI_WOM_5765,STRI_WOM_5766 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_phy -w 50000 -m 0 -T 1; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then python ~/work/scripts/creatFasta/createFastaMP_new.py -I ~/work/calls_eraNV/Herato_021016.$(echo $scaf).BEAGLE.calls.gz -iSample M_3654,M_3655,M_3656,M_3657,M_3659 -pC 0 -P ~/work/scripts/Popmap_new.txt -O ~/work/LDhelmet_out/$(echo $scaf)_ven -w 50000 -m 0 -T 1; fi

#if [ "$(echo "${inName[indID]}")" == 1 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_lat.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_lat.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_not.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_not.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_ama.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_ama.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_che.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_che.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_cyr.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_cyr.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_dem.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_dem.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_emm.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_emm.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_era.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_era.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_ety.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_ety.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_fav.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_fav.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_him.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_him.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_hydFG.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydFG.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_hydP.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydP.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_pet.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_pet.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_phy.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_phy.fasta; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then ldhelmet find_confs --num_threads 24 -w 50 -o ~/work/LDhelmet_out/$(echo $scaf)_ven.conf ~/work/LDhelmet_out/fasta/$(echo $scaf)_ven.fasta; fi


#if [ "$(echo "${inName[indID]}")" == 1 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_lat.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_lat.1k; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_not.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_not.1k; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ama.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_ama.1k; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_che.conf -t 0.02 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_che.1k; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_cyr.conf -t 0.02 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_cyr.1k; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_dem.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_dem.1k; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_emm.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_emm.1k; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_era.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_era.1k; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ety.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_ety.1k; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_fav.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_fav.1k; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_him.conf -t 0.02 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_him.1k; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_hydFG.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_hydFG.1k; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_hydP.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_hydP.1k; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_pet.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_pet.1k; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_phy.conf -t 0.03 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_phy.1k; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then ldhelmet table_gen --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ven.conf -t 0.02 -r 0.0 0.1 10.0 1.0 100.0 -o ~/work/LDhelmet_out/$(echo $scaf)_ven.1k; fi

#if [ "$(echo "${inName[indID]}")" == 1 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_lat.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_lat.pade; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_not.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_not.pade; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ama.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_ama.pade; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_che.conf -t 0.02 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_che.pade; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_cyr.conf -t 0.02 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_cyr.pade; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_dem.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_dem.pade; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_emm.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_emm.pade; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_era.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_era.pade; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ety.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_ety.pade; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_fav.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_fav.pade; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_him.conf -t 0.02 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_him.pade; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_hydFG.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_hydFG.pade; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_hydP.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_hydP.pade; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_pet.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_pet.pade; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_phy.conf -t 0.03 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_phy.pade; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then ldhelmet pade --num_threads 24 -c ~/work/LDhelmet_out/$(echo $scaf)_ven.conf -t 0.02 -x 11 -o ~/work/LDhelmet_out/$(echo $scaf)_ven.pade; fi


#if [ "$(echo "${inName[indID]}")" == 1 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_lat.1k -p ~/work/LDhelmet_out/$(echo $scaf)_lat.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_lat.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_lat_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_lat.post; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_not.1k -p ~/work/LDhelmet_out/$(echo $scaf)_not.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_not.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_not_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_not.post; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_ama.1k -p ~/work/LDhelmet_out/$(echo $scaf)_ama.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ama.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ama_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_ama.post; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_che.1k -p ~/work/LDhelmet_out/$(echo $scaf)_che.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_che.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_che_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_che.post; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_cyr.1k -p ~/work/LDhelmet_out/$(echo $scaf)_cyr.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_cyr.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_cyr_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_cyr.post; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_dem.1k -p ~/work/LDhelmet_out/$(echo $scaf)_dem.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_dem.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_dem_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_dem.post; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then ldhelmet rjmcmc --num_threads 32 -l ~/work/LDhelmet_out/$(echo $scaf)_emm.1k -p ~/work/LDhelmet_out/$(echo $scaf)_emm.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_emm.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_emm_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_emm.post; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_era.1k -p ~/work/LDhelmet_out/$(echo $scaf)_era.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_era.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_era_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_era.post; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_ety.1k -p ~/work/LDhelmet_out/$(echo $scaf)_ety.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ety.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ety_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_ety.post; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_fav.1k -p ~/work/LDhelmet_out/$(echo $scaf)_fav.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_fav.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_fav_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_fav.post; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_him.1k -p ~/work/LDhelmet_out/$(echo $scaf)_him.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_him.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_him_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_him.post; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_hydFG.1k -p ~/work/LDhelmet_out/$(echo $scaf)_hydFG.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydFG.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydFG_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_hydFG.post; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_hydP.1k -p ~/work/LDhelmet_out/$(echo $scaf)_hydP.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydP.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_hydP_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_hydP.post; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_pet.1k -p ~/work/LDhelmet_out/$(echo $scaf)_pet.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_pet.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_pet_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_pet.post; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_phy.1k -p ~/work/LDhelmet_out/$(echo $scaf)_phy.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_phy.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_phy_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_phy.post; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then ldhelmet rjmcmc --num_threads 24 -l ~/work/LDhelmet_out/$(echo $scaf)_ven.1k -p ~/work/LDhelmet_out/$(echo $scaf)_ven.pade -w 50 -b 50.0 --snps_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ven.fasta --pos_file ~/work/LDhelmet_out/fasta/$(echo $scaf)_ven_posList.txt -m ~/work/LDhelmet_out/mutMatrix/$(echo $scaf)mutMat.txt --burn_in 100000 -n 1000000 -o ~/work/LDhelmet_out/$(echo $scaf)_ven.post; fi

#if [ "$(echo "${inName[indID]}")" == 1 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_lat.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_lat.post; fi
#if [ "$(echo "${inName[indID]}")" == 2 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_not.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_not.post; fi
#if [ "$(echo "${inName[indID]}")" == 3 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_ama.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_ama.post; fi
#if [ "$(echo "${inName[indID]}")" == 4 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_che.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_che.post; fi
#if [ "$(echo "${inName[indID]}")" == 5 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_cyr.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_cyr.post; fi
#if [ "$(echo "${inName[indID]}")" == 6 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_dem.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_dem.post; fi
#if [ "$(echo "${inName[indID]}")" == 7 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_emm.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_emm.post; fi
#if [ "$(echo "${inName[indID]}")" == 8 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_era.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_era.post; fi
#if [ "$(echo "${inName[indID]}")" == 9 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_ety.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_ety.post; fi
#if [ "$(echo "${inName[indID]}")" == 10 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_fav.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_fav.post; fi
#if [ "$(echo "${inName[indID]}")" == 11 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_him.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_him.post; fi
#if [ "$(echo "${inName[indID]}")" == 12 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_hydFG.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_hydFG.post; fi
#if [ "$(echo "${inName[indID]}")" == 13 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_hydP.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_hydP.post; fi
#if [ "$(echo "${inName[indID]}")" == 14 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_pet.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_pet.post; fi
#if [ "$(echo "${inName[indID]}")" == 15 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_phy.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_phy.post; fi
#if [ "$(echo "${inName[indID]}")" == 16 ]; then ldhelmet post_to_text -m -p 0.025 -p 0.50 -p 0.975 -o ~/work/LDhelmet_out/$(echo $scaf)_ven.LDhelmet_summary.txt ~/work/LDhelmet_out/$(echo $scaf)_ven.post; fi

chromList=(Herato1 Herato2 Herato3 Herato4 Herato5 Herato6 Herato7 Herato8 Herato9 Herato10 Herato11 Herato12 Herato13 Herato14 Herato15 Herato16 Herato17 Herato18 Herato19 Herato20 Herato21)
scafList=(Herato01 Herato02 Herato03 Herato04 Herato05 Herato06 Herato07 Herato08 Herato09 Herato10 Herato11 Herato12 Herato13 Herato14 Herato15 Herato16 Herato17 Herato18 Herato19 Herato20 Herato21)

for i in {0..20}
do
if [ "$(echo "${inName[indID]}")" == 1 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_lat.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_lat.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 2 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_not.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_not.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 3 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ama.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ama.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 4 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_che.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_che.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 5 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_cyr.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_cyr.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 6 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_dem.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_dem.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 7 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_emm.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_emm.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 8 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_era.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_era.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 9 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ety.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ety.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 10 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_fav.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_fav.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 11 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_him.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_him.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 12 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_hydFG.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_hydFG.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 13 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_hydP.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_hydP.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 14 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_pet.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_pet.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 15 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_phy.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_phy.LDhelmet_summary50k.txt; fi
if [ "$(echo "${inName[indID]}")" == 16 ]; then python ~/work/scripts/windowLDhelmet.py -I ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ven.LDhelmet_summary.txt -S ~/work/scripts/scaffold_lengths_chrom.txt -w 50000 -chr $(echo "${scafList[$i]}") > ~/work/LDhelmet_out/$(echo "${chromList[$i]}")_ven.LDhelmet_summary50k.txt; fi
done


